name: Python application test with Github Actions

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-verision: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: | 
        male lint
    - name: test with pytest
      run: |
    - name: Format code  
      run: |
        male format
